/**
 * Central permission catalogue.
 * Every server action resolves one of these keys — the UI only mirrors them.
 */

export const PERMISSIONS = {
  // Dashboard / global
  DASHBOARD_VIEW: "dashboard.view",
  SEARCH_GLOBAL: "search.global",

  // Assets
  ASSETS_VIEW: "assets.view",
  ASSETS_CREATE: "assets.create",
  ASSETS_UPDATE: "assets.update",
  ASSETS_DELETE: "assets.delete",
  ASSETS_ASSIGN: "assets.assign",
  ASSETS_TRANSFER: "assets.transfer",
  ASSETS_DISPOSE: "assets.dispose",
  ASSETS_EXPORT: "assets.export",
  ASSETS_PRINT_LABELS: "assets.print_labels",

  // Consumable inventory
  INVENTORY_VIEW: "inventory.view",
  INVENTORY_RECEIVE: "inventory.receive",
  INVENTORY_ISSUE: "inventory.issue",
  INVENTORY_ADJUST: "inventory.adjust",
  INVENTORY_EXPORT: "inventory.export",

  // Assignments / clearance
  ASSIGNMENTS_VIEW: "assignments.view",
  ASSIGNMENTS_CREATE: "assignments.create",
  ASSIGNMENTS_RETURN: "assignments.return",
  ASSIGNMENTS_CLEARANCE: "assignments.clearance",

  // Transfers
  TRANSFERS_VIEW: "transfers.view",
  TRANSFERS_CREATE: "transfers.create",
  TRANSFERS_APPROVE: "transfers.approve",
  TRANSFERS_SHIP: "transfers.ship",
  TRANSFERS_RECEIVE: "transfers.receive",

  // Maintenance
  MAINTENANCE_VIEW: "maintenance.view",
  MAINTENANCE_MANAGE: "maintenance.manage",

  // Procurement
  SUPPLIERS_VIEW: "suppliers.view",
  SUPPLIERS_MANAGE: "suppliers.manage",
  PURCHASE_ORDERS_MANAGE: "purchase_orders.manage",

  // People
  EMPLOYEES_VIEW: "employees.view",
  EMPLOYEES_MANAGE: "employees.manage",

  // Organisation
  ORG_VIEW: "org.view",
  ORG_MANAGE: "org.manage",
  CATALOG_MANAGE: "catalog.manage",

  // Reports / audit / admin
  REPORTS_VIEW: "reports.view",
  REPORTS_EXPORT: "reports.export",
  AUDIT_VIEW: "audit.view",
  USERS_MANAGE: "users.manage",
  ROLES_MANAGE: "roles.manage",
  NOTIFICATIONS_MANAGE: "notifications.manage",
  DIAGNOSTICS_VIEW: "diagnostics.view",
  SETTINGS_MANAGE: "settings.manage",

  // Self service (every authenticated user)
  SELF_SERVICE_VIEW: "selfservice.view",
  SELF_SERVICE_REQUEST: "selfservice.request",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: PermissionKey[] = Object.values(PERMISSIONS);

const {
  DASHBOARD_VIEW,
  SEARCH_GLOBAL,
  ASSETS_VIEW,
  ASSETS_CREATE,
  ASSETS_UPDATE,
  ASSETS_DELETE,
  ASSETS_ASSIGN,
  ASSETS_TRANSFER,
  ASSETS_DISPOSE,
  ASSETS_EXPORT,
  ASSETS_PRINT_LABELS,
  INVENTORY_VIEW,
  INVENTORY_RECEIVE,
  INVENTORY_ISSUE,
  INVENTORY_ADJUST,
  INVENTORY_EXPORT,
  ASSIGNMENTS_VIEW,
  ASSIGNMENTS_CREATE,
  ASSIGNMENTS_RETURN,
  ASSIGNMENTS_CLEARANCE,
  TRANSFERS_VIEW,
  TRANSFERS_CREATE,
  TRANSFERS_APPROVE,
  TRANSFERS_SHIP,
  TRANSFERS_RECEIVE,
  MAINTENANCE_VIEW,
  MAINTENANCE_MANAGE,
  SUPPLIERS_VIEW,
  SUPPLIERS_MANAGE,
  PURCHASE_ORDERS_MANAGE,
  EMPLOYEES_VIEW,
  EMPLOYEES_MANAGE,
  ORG_VIEW,
  CATALOG_MANAGE,
  REPORTS_VIEW,
  REPORTS_EXPORT,
  AUDIT_VIEW,
  USERS_MANAGE,
  NOTIFICATIONS_MANAGE,
  DIAGNOSTICS_VIEW,
  SETTINGS_MANAGE,
  SELF_SERVICE_VIEW,
  SELF_SERVICE_REQUEST,
} = PERMISSIONS;

export const ROLE_KEYS = [
  "SUPER_ADMIN",
  "INVENTORY_ADMIN",
  "SITE_ADMIN",
  "TECHNICIAN",
  "DEPARTMENT_MANAGER",
  "INVENTORY_STAFF",
  "AUDITOR",
  "EMPLOYEE",
] as const;

export type RoleKey = (typeof ROLE_KEYS)[number];

export const ROLE_DEFINITIONS: Record<
  RoleKey,
  { name: string; description: string; siteScoped: boolean; permissions: PermissionKey[] }
> = {
  SUPER_ADMIN: {
    name: "Super Admin",
    description: "Full system access across every site and configuration surface.",
    siteScoped: false,
    permissions: ALL_PERMISSIONS,
  },
  INVENTORY_ADMIN: {
    name: "Inventory Administrator",
    description: "Manages inventory, assets, transfers, procurement and reports for all sites.",
    siteScoped: false,
    permissions: [
      DASHBOARD_VIEW,
      SEARCH_GLOBAL,
      ASSETS_VIEW,
      ASSETS_CREATE,
      ASSETS_UPDATE,
      ASSETS_DELETE,
      ASSETS_ASSIGN,
      ASSETS_TRANSFER,
      ASSETS_DISPOSE,
      ASSETS_EXPORT,
      ASSETS_PRINT_LABELS,
      INVENTORY_VIEW,
      INVENTORY_RECEIVE,
      INVENTORY_ISSUE,
      INVENTORY_ADJUST,
      INVENTORY_EXPORT,
      ASSIGNMENTS_VIEW,
      ASSIGNMENTS_CREATE,
      ASSIGNMENTS_RETURN,
      ASSIGNMENTS_CLEARANCE,
      TRANSFERS_VIEW,
      TRANSFERS_CREATE,
      TRANSFERS_APPROVE,
      TRANSFERS_SHIP,
      TRANSFERS_RECEIVE,
      MAINTENANCE_VIEW,
      MAINTENANCE_MANAGE,
      SUPPLIERS_VIEW,
      SUPPLIERS_MANAGE,
      PURCHASE_ORDERS_MANAGE,
      EMPLOYEES_VIEW,
      EMPLOYEES_MANAGE,
      ORG_VIEW,
      CATALOG_MANAGE,
      REPORTS_VIEW,
      REPORTS_EXPORT,
      AUDIT_VIEW,
      NOTIFICATIONS_MANAGE,
      SELF_SERVICE_VIEW,
      SELF_SERVICE_REQUEST,
    ],
  },
  SITE_ADMIN: {
    name: "Site Administrator",
    description: "Manages inventory belonging to the sites they are scoped to.",
    siteScoped: true,
    permissions: [
      DASHBOARD_VIEW,
      SEARCH_GLOBAL,
      ASSETS_VIEW,
      ASSETS_CREATE,
      ASSETS_UPDATE,
      ASSETS_ASSIGN,
      ASSETS_TRANSFER,
      ASSETS_PRINT_LABELS,
      ASSETS_EXPORT,
      INVENTORY_VIEW,
      INVENTORY_RECEIVE,
      INVENTORY_ISSUE,
      INVENTORY_ADJUST,
      INVENTORY_EXPORT,
      ASSIGNMENTS_VIEW,
      ASSIGNMENTS_CREATE,
      ASSIGNMENTS_RETURN,
      ASSIGNMENTS_CLEARANCE,
      TRANSFERS_VIEW,
      TRANSFERS_CREATE,
      TRANSFERS_SHIP,
      TRANSFERS_RECEIVE,
      MAINTENANCE_VIEW,
      MAINTENANCE_MANAGE,
      SUPPLIERS_VIEW,
      EMPLOYEES_VIEW,
      ORG_VIEW,
      REPORTS_VIEW,
      REPORTS_EXPORT,
      SELF_SERVICE_VIEW,
      SELF_SERVICE_REQUEST,
    ],
  },
  TECHNICIAN: {
    name: "IT / Technician",
    description: "Manages IT assets, diagnostics and maintenance tickets.",
    siteScoped: true,
    permissions: [
      DASHBOARD_VIEW,
      SEARCH_GLOBAL,
      ASSETS_VIEW,
      ASSETS_UPDATE,
      ASSETS_ASSIGN,
      ASSETS_PRINT_LABELS,
      INVENTORY_VIEW,
      ASSIGNMENTS_VIEW,
      ASSIGNMENTS_RETURN,
      TRANSFERS_VIEW,
      TRANSFERS_RECEIVE,
      MAINTENANCE_VIEW,
      MAINTENANCE_MANAGE,
      SUPPLIERS_VIEW,
      EMPLOYEES_VIEW,
      ORG_VIEW,
      REPORTS_VIEW,
      SELF_SERVICE_VIEW,
      SELF_SERVICE_REQUEST,
    ],
  },
  DEPARTMENT_MANAGER: {
    name: "Department Manager",
    description: "Reviews and approves assignments and transfers for their department.",
    siteScoped: true,
    permissions: [
      DASHBOARD_VIEW,
      SEARCH_GLOBAL,
      ASSETS_VIEW,
      ASSETS_ASSIGN,
      INVENTORY_VIEW,
      ASSIGNMENTS_VIEW,
      ASSIGNMENTS_CREATE,
      ASSIGNMENTS_RETURN,
      TRANSFERS_VIEW,
      TRANSFERS_CREATE,
      TRANSFERS_APPROVE,
      MAINTENANCE_VIEW,
      EMPLOYEES_VIEW,
      ORG_VIEW,
      REPORTS_VIEW,
      SELF_SERVICE_VIEW,
      SELF_SERVICE_REQUEST,
    ],
  },
  INVENTORY_STAFF: {
    name: "Inventory Staff",
    description: "Receives, issues, assigns and updates inventory on the floor.",
    siteScoped: true,
    permissions: [
      DASHBOARD_VIEW,
      SEARCH_GLOBAL,
      ASSETS_VIEW,
      ASSETS_CREATE,
      ASSETS_UPDATE,
      ASSETS_ASSIGN,
      ASSETS_PRINT_LABELS,
      INVENTORY_VIEW,
      INVENTORY_RECEIVE,
      INVENTORY_ISSUE,
      INVENTORY_ADJUST,
      ASSIGNMENTS_VIEW,
      ASSIGNMENTS_CREATE,
      ASSIGNMENTS_RETURN,
      TRANSFERS_VIEW,
      TRANSFERS_CREATE,
      TRANSFERS_SHIP,
      TRANSFERS_RECEIVE,
      MAINTENANCE_VIEW,
      SUPPLIERS_VIEW,
      EMPLOYEES_VIEW,
      ORG_VIEW,
      SELF_SERVICE_VIEW,
      SELF_SERVICE_REQUEST,
    ],
  },
  AUDITOR: {
    name: "Auditor",
    description: "Read-only access to inventory, reports and the audit trail.",
    siteScoped: false,
    permissions: [
      DASHBOARD_VIEW,
      SEARCH_GLOBAL,
      ASSETS_VIEW,
      ASSETS_EXPORT,
      INVENTORY_VIEW,
      INVENTORY_EXPORT,
      ASSIGNMENTS_VIEW,
      TRANSFERS_VIEW,
      MAINTENANCE_VIEW,
      SUPPLIERS_VIEW,
      EMPLOYEES_VIEW,
      ORG_VIEW,
      REPORTS_VIEW,
      REPORTS_EXPORT,
      AUDIT_VIEW,
      SELF_SERVICE_VIEW,
    ],
  },
  EMPLOYEE: {
    name: "Employee",
    description: "Self-service portal: view assigned assets, request returns and repairs.",
    siteScoped: false,
    permissions: [SELF_SERVICE_VIEW, SELF_SERVICE_REQUEST],
  },
};

/** Keys used by the sidebar / command palette for visibility filtering. */
export const NAV_PERMISSIONS: Record<string, PermissionKey> = {
  dashboard: DASHBOARD_VIEW,
  assets: ASSETS_VIEW,
  inventory: INVENTORY_VIEW,
  transfers: TRANSFERS_VIEW,
  assignments: ASSIGNMENTS_VIEW,
  maintenance: MAINTENANCE_VIEW,
  suppliers: SUPPLIERS_VIEW,
  employees: EMPLOYEES_VIEW,
  reports: REPORTS_VIEW,
  audit: AUDIT_VIEW,
  org: ORG_VIEW,
  users: USERS_MANAGE,
  notifications: NOTIFICATIONS_MANAGE,
  diagnostics: DIAGNOSTICS_VIEW,
  settings: SETTINGS_MANAGE,
  selfservice: SELF_SERVICE_VIEW,
};
